# Generated by Django 2.2.5 on 2019-09-17 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190917_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete='models.PROTECT', related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
