# Generated by Django 2.2.5 on 2019-09-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
